# Site settings
title: Caleydo
email: contact@caleydo.org
description: "Caleydo: Visualization for BioMedicine."
baseurl: ""
url: "http://caleydo.org"
twitter_username: caleydo_org
github_username:  caleydo
youtube_username: caleydotugraz
facebook_page: Caleydo/110550618994500
license_url: https://raw.githubusercontent.com/Caleydo/caleydo/develop/LICENSE
safe: false
lsi: false
google_analytics: "'UA-45998043-1'"
use_analytics: true

paper_content_url: http://data.caleydo.org/papers/
data_url: http://data.caleydo.org/

# Build settings

permalink: pretty
sass:
  sass_dir: _sass
# exclude from build
exclude: ["README.md", "Rakefile", "changelog.md", ".idea/", "Gemfile", "Gemfile.lock", "rvm.env", "vendor"]

# code highlighter
#highlighter: rouge

# Collections
collections:
  tools:
    output: true
    permalink: /tools/:path/
  themes:
    output: true
    permalink: /:path/
  persons:
    output: false
    permalink: /persons/:path/
  publications:
    output: true
    permalink: /publications/:path/
  thesis:
    output: true
    permalink: /thesis/:path/
  releases:
    output: true
    permalink: /releases/:path/
  videos:
    output: false
    permalink: /videos/:path/
  datasets:
    output: false
    permalink: /datasets/:path/
  institutions:
    output: false
    permalink: /institutions/:path/
  funding:
    output: false
    permalink: /funding/:path/
